### PR TITLE
Create suru-first-test

### PR DESCRIPTION
**Pull request by mivoligo**
10 symbols made from suru icons

### CODE REVIEW

**Comment by Xaviju** [comment]
Hi @mivoligo 
I've just tested the icons. They look like this: some have colors, some don't. Is that correct?



Note: Remember to add the icons to a folder named ```suru-icons```. And remember that the icons should have a ```.svg``` extension or they won't load in inkscape.

If they look good to you ypu can keep doing them, I will check them out after your complete pull request and make som minor fixes.

:cool: Thanks!

**Comment by mivoligo** [comment]
Hi @Xaviju 
Colors are correct on your screenshot. Some of the icons are, in fact, not grey.
I'll try to finish part of them tomorrow.

**Comment by Xaviju** [comment]
Can I close this PR? I assume the other PR is the good one.

**Comment by mivoligo** [comment]
Sure, go ahead. As I mentioned I'm not very good at using github :)

**Comment by Xaviju** [comment]
Nice, thanks @mivoligo :)

**Pull request closed without merging**
