### PR TITLE
add suru icons

### PR DESCRIPTION
**Pull request by mivoligo**

### CODE REVIEW

**Comment by mivoligo** [comment]
@Xaviju There's one more set to do. I'll try to do it later today.

**Comment by Xaviju** [comment]
Looks great! I'll merge it as soon as you add the last set! :smiley:

**Comment by mivoligo** [comment]
ok, I've just added the last set

**Comment by Xaviju** [comment]
@mivoligo I'll test it as soon as possible (probably tonight) and merge it if everything works fine.

:+1:

**Comment by Xaviju** [comment]
Merged! The only thing I miss is that I cannot directly edit its colors because of the SVG code (it has the styles inlined). If you agree I will add a issue to fx the styles and make the icons color editable.

:+1: Thanks @mivoligo

**Comment by mivoligo** [comment]
Thanks for merging! About editing the colors: is there any automatic way to clean the code to make it possible? What about icons with more than one color?

**Comment by Xaviju** [comment]
I will keep the icons with colors as they are, but will remove the single-color styles to make them editable. Need to learn how to do it to make all of them editable and keep the colors but not sure how. If I don't find the way to do it I will leave them like that. :)

**Comment by Xaviju** [comment]
About an automatic way: If I have time this weekend I will try to investigate it.

Thank you for this icons, are awesome!

**Comment by mivoligo** [comment]
OK, great, let me know how it goes.

**Pull request merged**
