### PR TITLE
Sjjb icons

### PR DESCRIPTION
**Pull request by Moini**
The icons are now complete, but they may still require some cleaning (I think the inverted ones are fine aside from xml declaration, but the others may need some styles removed - for the square ones, please keep fill, if it's set to white, and opacity).

I've also edited the licences section of the README, and added the new icon set there. 

This was done in a way that assumes that each subfolder (accomodation, transport, food, ....) will get its own iconset file (or the icons in the folder of the same name for inverted and square could also be put together into one iconset file). If you'd prefer to put them all into one, please let me know, then I'll adapt the text accordingly.

The two template files contain the basic text and licence info. They are currently separated by set (square / inverted), and there isn't one for each icon subject (I thought it might be quicker to generate them automatically, if desired).

Please let me know if this is enough for you to go on, or if there's more that I should do.

### CODE REVIEW

**Comment by Moini** [comment]
I also changed the Humble UI license in the README to the licence given in the svg file (so it changed from CC-By-SA 4.0 to MIT). Hope that was correct? There's no licence on the linked Wiki page, so that was the only source I had.

**Comment by Xaviju** [comment]
I'll check the Pull request code as soon as possible. Thanks for the language fixes

**Comment by Moini** [comment]
Thank you - I know it's a lot, take your time!

**Comment by Moini** [comment]
Unrelated, but thought you might like to know: your icon set is mentioned here:
https://opensource.com/article/16/12/yearbook-top-open-source-creative-tools-2016

**Comment by Xaviju** [comment]
Oh, wow. Thanks for the link! :heart_eyes: 
I was looking at the pull request right now.

**Comment by Xaviju** [comment]
@Moini Oh, i think I closed this involuntarily. Can you make the pull request again?

**Comment by Moini** [comment]
Seems it still worked somehow. Git magic ;-)

**Pull request closed without merging**
