### PR TITLE
Added a set of weather icons I created and packaged

### PR DESCRIPTION
**Pull request by jlar0che**
I created a set of Weather Icons and packaged them into a single svg file in order to fulfill the promise of an upcoming Weather set (which is stated in the Readme file). 

**EXTRA INFO:** I read the article by Xaviju on Medium (How to create a symbol library in inkscape 0.91) and used the symbol.basic.svg file provided in that article as a template.

### CODE REVIEW

**Comment by Xaviju** [comment]
Great! Its almost done. Just some small fixes:

- There should be only one ```<defs>``` wrapping the ```<symbols>```
- Every ```symbol``` should be closed (some of them are still open so the code is broken).
- If your symbol ```paths``` have a ```fill``` or ```stroke``` attribute they will use colors, and you won't be able to edit the symbol colors in Inkscape. I tend to remove those attributes if are not completely necessary to understand the meaning of the icon.

If you have any problems, I'll help you. :)
Thanks again for your help.

**Comment by jlar0che** [comment]
You're welcome.

I made all the edits you pointed out and sent another pull request.

One question though: Github didn't count my new pull request as a new
contribution. Would you happen to know why?

Take care!

**Comment by Xaviju** [comment]
Looks great!
I guess Github will count it as soon as I merge this pull request. You made two commits in one pull request.
:clap:

**Comment by jlar0che** [comment]
Super! They did add it!

Cool. Now that I have a good working knowledge of making these symbol sets
I'll work on making some more soon.

Take it easy,

-Jacques

**Comment by Xaviju** [comment]
Please give me more info about: 
- Icon set name
- creator
- license
- url

So I can add it to the ```readme```

**Comment by jlar0che** [comment]
Icon Set Name: Weatherize
Creator: Jacques Laroche
License: Open Source
URL: none yet, but once I make one i'll let you know

**Pull request merged**
