### PR TITLE
Fix broken CircuiTikZ icons due to style specification

### PR DESCRIPTION
**Pull request by joel-jose**
Changed `style=style="fill:black;stroke:none"` to `style="fill:none;stroke:black; stroke-width:3px;"`

### CODE REVIEW

**Comment by Xaviju** [comment]
Thanks @joel-jose ¿would you mind squashing your commits into a single commit and rebasing master before merging?

**Comment by Xaviju** [comment]
@joel-jose will you be able to check this?

**Comment by Xaviju** [comment]
Closing this PR since there is no response from @joel-jose 
Fixed styles in master already

**Comment by joel-jose** [comment]
Sorry I was away for some time :(

**Pull request closed without merging**
