### PR TITLE
Fixes warnings in inkscape console because namespaces

### PR DESCRIPTION
**Pull request by jabiertxof**
Title autodescriptive

### CODE REVIEW

**Comment by Xaviju** [comment]
This is so awesome I'm almost crying. I'll tests it ASAP.

Would you mind checking the template file as well? I use it as an example for newcomers: https://raw.githubusercontent.com/Xaviju/inkscape-open-symbols/master/template.svg

¡GRACIAS!

**Comment by Moini** [comment]
Isn't it already in the diff?
https://github.com/Xaviju/inkscape-open-symbols/pull/77/commits/88b3d11d95b30cc2a9269f682fdfe4acd7bad261#diff-d67fb6aacbcb7054c1a8616c6520461f

**Comment by Xaviju** [comment]
Oh sorry, I didn't see it! I'll test it tomorrow. :D

**Comment by PanderMusubi** [comment]
@Xaviju, completely off-topic, but your comment triggered it, check your LinkedIn.

**Comment by Xaviju** [comment]
Awesome, thanks @jabiertxof

**Comment by jabiertxof** [comment]
You are welcome!

**Pull request merged**
