### PR TITLE
Language cleanup and typo fixes, along with slight modifications and …

### PR DESCRIPTION
**Pull request by jlar0che**
…additions to the Readme file.

When looking at the Readme file for this project while figuring out how I could contribute I was very confused by the language and layout. I thought it could have been put a better way and also saw many typos and language issues - so I decided to fix it.

### CODE REVIEW

**Comment by Xaviju** [comment]
Thanks @jlar0che!

**Comment by jlar0che** [comment]
Anytime. I'd like to also point out that the following sentence is still
not very clear, and I couldn't really fix it because I couldn't make sense
of it:

*"*It is perfectly fine to use the Inkscape UI for library development, but
they won't be as useful for developers as it is well generated, minimized
and packed for use in production development in some cases.

*Some icons need to be SVG processed in order to be fully useful for both
for designers and developers."*
I also put together a few Weather icons and sent a pull request for that.

*Take care!*

**Comment by Xaviju** [comment]
I'll try to explain the sentences. If you have a better way of expressing it I'll be happy to edit it.

> It is perfectly fine to use the Inkscape UI for library development, but
they won't be as useful for developers as it is well generated, minimized
and packed for use in production development in some cases.

What I mean is that you can use the inkscape UI to generate symbols libraries. However, if those icons are used by web developers, they won't be able to use it right away in production. Following my article, the symbols generated will be ready for production in web environments as well as inkscape.

 > Some icons need to be SVG processed in order to be fully useful for both
for designers and developers.

The symbols are usually simplified to be used in web environments to remove unnecessary complexities in the generated code. 

Thanks again

**Comment by jlar0che** [comment]
Thanks for that. I'll think about it and if any edits come to mind I'll
send another PR.

-Jacques

**Pull request merged**
