### PR TITLE
Sjjb icons

### PR DESCRIPTION
**Pull request by Xaviju**

### CODE REVIEW

**Comment by Xaviju** [comment]
@Moini great, I made the pull request again from you repo!

**Comment by Xaviju** [comment]
@Moini could you review the conflict before merging? Not sure what happened.

**Comment by Moini** [comment]
Done. Seems I lost the license of two icon sets along the way... They're back now, with more precise info.

**Comment by Xaviju** [comment]
Merged! I'll make the fine tuning on master and create the final sprite!

**Comment by Moini** [comment]
Thanks a lot, @Xaviju ! Looking forward to trying it out :)

**Pull request merged**
